version: "3.8"
services:
  server:
    build: .
    volumes:
      - ./:/app
    ports:
      - 8080:3000
    env_file:
      - .env
    links:
      - database
    command: [ "npm", "start" ]
  database:
    image: postgres:14.1-alpine
    container_name: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data
volumes:
  database-data: { }