version: "3"
services:
  server:
    build: .
    volumes:
      - ./:/app
    ports:
      - 8080:3000
    env_file:
      - .env
    links:
      - database
    command: [ "npm", "start" ]
  database:
    image: postgres:9.6-alpine
    container_name: postgres
    ports:
      - '5436:5431'
    volumes:
      - database-data:/var/lib/postgresql/data
volumes:
  database-data: { }