version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./:/app
      - ./nodemon.json:/home/node/app/nodemon.json
    ports:
      - "8080:3000"
    expose:
      - "3000"
    env_file:
      - .env
    depends_on:
      - database
    command: npm run dev
  database:
    image: postgres:14.1-alpine
    container_name: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data
volumes:
  database-data: { }